### ISSUE TITLE
Problem with "delete" malt

### ISSUE THREAD

**Issue by fangirsan** [fangirsan/maruszka-new#5]
Fri May 17 21:30:57 CEST 2019
There was an unexpected error (type=Internal Server Error, status=500).
could not execute statement; SQL [n/a]; constraint ["FKM636T1NDS3GNKJC6WG8MCG21L: PUBLIC.BATCH_MALT FOREIGN KEY(MALT_ID) REFERENCES PUBLIC.MALT(ID) (2)"; SQL statement: delete from malt where id=? [23503-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["FKM636T1NDS3GNKJC6WG8MCG21L: PUBLIC.BATCH_MALT FOREIGN KEY(MALT_ID) REFERENCES PUBLIC.MALT(ID) (2)"; SQL statement:
delete from malt where id=? [23503-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:296)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:536)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:533)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)

**Comment by fangirsan** [comment]
MaltSDJpaService
@Override
public void deleteById(Long maltIdToDelete) {
	
	Set<Batch> batches = batchRepository.findByMalts_id(maltIdToDelete);
	
	if (batches != null) {
		for (Batch tempBatch : batches) {
			Optional<Malt> maltOptional = tempBatch
				.getMalts()
				.stream()
				.filter(malt -> malt.getId().equals(maltIdToDelete))
				.findFirst();
			
			if (maltOptional.isPresent()) {
				Malt maltToDelete = maltOptional.get();
				maltToDelete.setBatches(null);
				tempBatch.getMalts().remove(maltOptional.get());
				batchRepository.save(tempBatch);
			}
		}
		maltRepository.deleteById(maltIdToDelete);
	}
}

BatchRepository
Set<Batch> findByMalts_id(Long maltId);
